name: portfolio-dev
version: '3'
services:
  db:
    image: mysql:9.5
    container_name: portfolio_db_dev
    ports:
      - "3308:3306"
    env_file:
      - ../.env.dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data_dev:/var/lib/mysql

  shadow_db:
    image: mysql:9.5
    container_name: portfolio_shadow_db_dev
    ports:
      - "3309:3306"
    env_file:
      - ../.env.dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_SHADOW_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - shadow_db_data_dev:/var/lib/mysql
    depends_on:
      - db
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: portfolio_app_dev
    ports:
      - "3001:3000"
    env_file:
      - ../.env.dev
    depends_on:
      - db
      - shadow_db

volumes:
  db_data_dev:
  shadow_db_data_dev: